Models/ErrorViewModel.cs
namespace efcoreApp.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

Controllers/CourseController.cs
using efcoreApp.Data;
using Microsoft.AspNetCore.Http.HttpResults;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace efcoreApp.Controllers
{
    public class CourseController : Controller
    {
        private readonly DataContext _context;

        public CourseController(DataContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            return View(await _context.Courses.ToListAsync());
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(Course model)
        {
            _context.Courses.Add(model);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null) return NotFound();

            var course = await _context.Courses.FindAsync(id);
            if (course == null) return NotFound();

            return View(course);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, Course model)
        {
            if (id != model.CourseId) return NotFound();

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(model);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateException)
                {
                    if (!_context.Courses.Any(c => c.CourseId == model.CourseId)) return NotFound();
                    else throw;
                }

                return RedirectToAction("Index");
            }

            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null) return NotFound();

            var course = await _context.Courses.FindAsync(id);
            if (course == null) return NotFound();

            return View(course);
        }

        [HttpPost]
        public async Task<IActionResult> Delete([FromForm]int id)
        {
            var course = await _context.Courses.FindAsync(id);
            if (course == null) return NotFound();

            _context.Courses.Remove(course);
            await _context.SaveChangesAsync();

            return RedirectToAction("Index");
        }
    }
}

Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using efcoreApp.Models;

namespace efcoreApp.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Controllers/StudentController.cs
using efcoreApp.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace efcoreApp.Controllers
{
    public class StudentController : Controller
    {
        private readonly DataContext _context;

        public StudentController(DataContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            return View(await _context.Students.ToListAsync());
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(Student model)
        {
            _context.Students.Add(model);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null) return NotFound();

            var student = await _context.Students.FindAsync(id);
            // var student = await _context.Students.FirstOrDefaultAsync(s => s.StudentId == id);
            if (student == null) return NotFound();

            return View(student);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, Student model)
        {
            if (id != model.StudentId) return NotFound();

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(model);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!_context.Students.Any(s => s.StudentId == model.StudentId)) return NotFound();
                    else throw;
                }

                return RedirectToAction("Index");
            }

            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null) return NotFound();

            var student = await _context.Students.FindAsync(id);
            if (student == null) return NotFound();

            return View(student);
        }
        
        [HttpPost]
        public async Task<IActionResult> Delete([FromForm]int id)
        {
            var student = await _context.Students.FindAsync(id);
            if (student == null) return NotFound();

            _context.Students.Remove(student);
            await _context.SaveChangesAsync();

            return RedirectToAction("Index");
        }
    }
}

Views/Course/Create.cshtml
@model Course

@{
    ViewData["Title"] = "Yeni Kurs Ekle";
}

<form asp-controller="Course" asp-action="Create" method="post">
    <div class="mb-3">
        <label asp-for="Name" class="form-label">Kurs Adı</label>
        <input asp-for="Name" class="form-control">
    </div>

    <button type="submit" class="btn btn-success">Kaydet</button>
</form>

Views/Course/Delete.cshtml
@model Course

@{
    ViewData["Title"] = "Kurs Kayıt Sil";
}

<p>
    <b>@Model.Name</b> isimli kursu silmek istiyor musunuz?

    <form asp-action="Delete" method="post">
        <input type="hidden" name="id" value="@Model.CourseId">
        <button type="submit" class="btn btn-success">Evet</button>
        <a asp-action="Index" class="btn btn-danger">Hayır</a>
    </form>
</p>

Views/Course/Edit.cshtml
@model Course

@{
    ViewData["Title"] = "Kurs Bilgi Düzenle";
}

<form asp-controller="Course" asp-action="Edit" method="post">
    <input type="hidden" asp-for="CourseId">
    <div class="mb-3">
        <label asp-for="Name" class="form-label">Ad</label>
        <input asp-for="Name" class="form-control">
    </div>

    <button type="submit" class="btn btn-success">Güncelle</button>
</form>

Views/Course/Index.cshtml
@model IEnumerable<Course>

@{
    ViewData["Title"] = "Kurs Listesi";
}

<h2>Kurs Listesi</h2>
<a asp-controller="Course" asp-action="Create" class="btn btn-success">Yeni Kurs Ekle</a>
<hr>
<table class="table table-bordered">
    <thead>
        <tr>
            <th style="width: 150px;">@Html.DisplayNameFor(m => m.CourseId)</th>
            <th>@Html.DisplayNameFor(m => m.Name)</th>
            <th style="width: 150px;">İşlemler</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var course in Model) {
            <tr>
                <td>@Html.DisplayFor(item => course.CourseId)</td>
                <td>@Html.DisplayFor(item => course.Name)</td>
                <td>
                    <a asp-controller="Course" asp-action="Edit" asp-route-id="@course.CourseId" class="btn btn-primary">Düzenle</a>
                    <a asp-controller="Course" asp-action="Delete" asp-route-id="@course.CourseId" class="btn btn-danger">Sil</a>
                </td>
            </tr>
        }
    </tbody>
</table>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - efcoreApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/efcoreApp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">efcoreApp</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Student" asp-action="Index">Öğrenciler</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Course" asp-action="Index">Kurslar</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - efcoreApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Student/Create.cshtml
@model Student

@{
    ViewData["Title"] = "Yeni Öğrenci Ekle";
}

<form asp-controller="Student" asp-action="Create" method="post">
    <div class="mb-3">
        <label asp-for="Firstname" class="form-label">Ad</label>
        <input asp-for="Firstname" class="form-control">
    </div>
    <div class="mb-3">
        <label asp-for="Lastname" class="form-label">Soyad</label>
        <input asp-for="Lastname" class="form-control">
    </div>
    <div class="mb-3">
        <label asp-for="Email" class="form-label">E-posta</label>
        <input asp-for="Email" class="form-control">
    </div>
    <div class="mb-3">
        <label asp-for="PhoneNumber" class="form-label">Telefon</label>
        <input asp-for="PhoneNumber" class="form-control">
    </div>

    <button type="submit" class="btn btn-success">Kaydet</button>
</form>

Views/Student/Delete.cshtml
@model Student

@{
    ViewData["Title"] = "Öğrenci Kayıt Sil";
}

<p>
    <b>@Model.Firstname @Model.Lastname</b> isimli öğrenciyi silmek istiyor musunuz?

    <form asp-action="Delete" method="post">
        <input type="hidden" name="id" value="@Model.StudentId">
        <button type="submit" class="btn btn-success">Evet</button>
        <a asp-action="Index" class="btn btn-danger">Hayır</a>
    </form>
</p>

Views/Student/Edit.cshtml
@model Student

@{
    ViewData["Title"] = "Öğrenci Bilgi Düzenle";
}

<form asp-controller="Student" asp-action="Edit" method="post">
    <input type="hidden" asp-for="StudentId">
    <div class="mb-3">
        <label asp-for="Firstname" class="form-label">Ad</label>
        <input asp-for="Firstname" class="form-control">
    </div>
    <div class="mb-3">
        <label asp-for="Lastname" class="form-label">Soyad</label>
        <input asp-for="Lastname" class="form-control">
    </div>
    <div class="mb-3">
        <label asp-for="Email" class="form-label">E-posta</label>
        <input asp-for="Email" class="form-control">
    </div>
    <div class="mb-3">
        <label asp-for="PhoneNumber" class="form-label">Telefon</label>
        <input asp-for="PhoneNumber" class="form-control">
    </div>

    <button type="submit" class="btn btn-success">Güncelle</button>
</form>

Views/Student/Index.cshtml
@model IEnumerable<Student>

@{
    ViewData["Title"] = "Öğrenci Listesi";
}

<h2>Öğrenci Listesi</h2>
<a asp-controller="Student" asp-action="Create" class="btn btn-success">Yeni Öğrenci Ekle</a>
<hr>
<table class="table table-bordered">
    <thead>
        <tr>
            <th style="width: 150px;">@Html.DisplayNameFor(m => m.StudentId)</th>
            <th>@Html.DisplayNameFor(m => m.Firstname)</th>
            <th>@Html.DisplayNameFor(m => m.Lastname)</th>
            <th style="width: 150px;">İşlemler</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var student in Model) {
            <tr>
                <td>@Html.DisplayFor(item => student.StudentId)</td>
                <td>@Html.DisplayFor(item => student.Firstname)</td>
                <td>@Html.DisplayFor(item => student.Lastname)</td>
                <td>
                    <a asp-controller="Student" asp-action="Edit" asp-route-id="@student.StudentId" class="btn btn-primary">Düzenle</a>
                    <a asp-controller="Student" asp-action="Delete" asp-route-id="@student.StudentId" class="btn btn-danger">Sil</a>
                </td>
            </tr>
        }
    </tbody>
</table>